# Generated by Django 4.2.7 on 2023-11-30 21:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mainapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=10, null=True, validators=[mainapp.models.validar_codigo])),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)])),
            ],
        ),
        migrations.CreateModel(
            name='Numero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('PA', 'Pagado'), ('RE', 'Reservado'), ('DI', 'Disponible')], default='DI', max_length=2)),
                ('id_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.compra')),
            ],
        ),
        migrations.CreateModel(
            name='Rifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=600)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('descripcion', models.CharField(max_length=1500)),
                ('imagen', models.ImageField(upload_to='images/rifa/')),
                ('estado', models.CharField(choices=[('OC', 'Oculta'), ('DI', 'Disponible'), ('FI', 'Finalizada'), ('AN', 'Anulada')], default='DI', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=1500)),
                ('imagen', models.ImageField(upload_to='images/premio/')),
                ('id_numero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.numero')),
                ('id_rifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.rifa')),
            ],
        ),
        migrations.AddField(
            model_name='numero',
            name='id_rifa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.rifa'),
        ),
    ]
